import React, { useState } from 'react';
import { 
  Terminal, Code2, Play, CheckCircle2, AlertTriangle, 
  Database, ArrowRight, Wand2, RefreshCw, FileCode, 
  GitBranch, Server, Bug, TestTube, Layers, FileJson,
  Braces, ShieldCheck, Sparkles, Shuffle
} from 'lucide-react';
import { 
  ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, 
  PieChart, Pie, Cell
} from 'recharts';

type Tab = 'CODEGEN' | 'TESTING' | 'MIGRATION';

// --- Windchill Code Generator View ---

const CodeGeneratorView = () => {
  const [prompt, setPrompt] = useState('');
  const [generatedCode, setGeneratedCode] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [codeType, setCodeType] = useState('Service');

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      // Simulation of Windchill specific code generation
      const mockCode = `package com.nexus.plm.service;

import wt.fc.PersistenceHelper;
import wt.fc.QueryResult;
import wt.part.WTPart;
import wt.util.WTException;
import wt.vc.config.LatestConfigSpec;

/**
 * Service to traverse BOM and identify buy-out parts.
 * Generated by Nexus AI Copilot
 */
public class BOMTraversalService {

    public static void getBuyOutParts(WTPart rootPart) throws WTException {
        // AI Note: Using LatestConfigSpec to get latest versions
        LatestConfigSpec configSpec = new LatestConfigSpec();
        QueryResult qr = WTPartHelper.service.getUsesWTParts(rootPart, configSpec);

        while (qr.hasMoreElements()) {
            Persistable[] link = (Persistable[]) qr.nextElement();
            WTPart child = (WTPart) link[1];

            // AI Logic: Check for 'Buy' source attribute
            String source = (String) IBAUtils.getIBAValue(child, "SOURCE_CODE");
            
            if ("BUY".equalsIgnoreCase(source)) {
                System.out.println("Found Buy-out Part: " + child.getNumber());
                // TODO: Add ERP Interface call logic here
            }
            
            // Recursive call for multi-level traversal
            getBuyOutParts(child);
        }
    }
}`;
      setGeneratedCode(mockCode);
      setIsGenerating(false);
    }, 1500);
  };

  const predefinedPrompts = [
    "创建一个递归遍历 BOM 的服务，查找所有外购件。",
    "编写一个 Action，用于在检入前校验文档属性完整性。",
    "生成一个数据加载器 (Loader)，从 CSV 批量创建 WTPart。"
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-full animate-in fade-in duration-500">
      {/* Left: Input & Config */}
      <div className="lg:col-span-4 space-y-6">
         <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-5">
            <h3 className="font-semibold text-white mb-4 flex items-center gap-2">
               <Terminal size={18} className="text-blue-400" />
               Windchill 代码生成器
            </h3>
            
            <div className="space-y-4">
               <div>
                  <label className="text-xs text-slate-500 block mb-1.5">组件类型</label>
                  <div className="flex bg-slate-950 p-1 rounded-lg border border-slate-800">
                     {['Service', 'Action', 'Loader'].map(t => (
                        <button 
                           key={t}
                           onClick={() => setCodeType(t)}
                           className={`flex-1 py-1.5 text-xs font-medium rounded transition-colors ${
                              codeType === t ? 'bg-slate-800 text-white shadow-sm' : 'text-slate-500 hover:text-slate-300'
                           }`}
                        >
                           {t}
                        </button>
                     ))}
                  </div>
               </div>

               <div>
                  <label className="text-xs text-slate-500 block mb-1.5">需求描述 (Natural Language)</label>
                  <textarea 
                     value={prompt}
                     onChange={(e) => setPrompt(e.target.value)}
                     className="w-full h-32 bg-slate-950 border border-slate-700 rounded-lg p-3 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:border-blue-500 resize-none"
                     placeholder="例如：编写一个服务，递归遍历 BOM 结构，返回所有 '外购' 类型的部件..."
                  />
               </div>

               <div className="space-y-2">
                  <div className="text-[10px] text-slate-500 uppercase font-semibold">快速填充</div>
                  {predefinedPrompts.map((p, i) => (
                     <button key={i} onClick={() => setPrompt(p)} className="w-full text-left p-2 bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-slate-700 rounded text-xs text-slate-400 truncate transition-colors">
                        {p}
                     </button>
                  ))}
               </div>

               <button 
                  onClick={handleGenerate}
                  disabled={isGenerating || !prompt}
                  className="w-full py-2.5 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-600 text-white text-sm font-medium rounded-lg flex items-center justify-center gap-2 transition-colors shadow-lg shadow-indigo-500/20"
               >
                  {isGenerating ? (
                     <><RefreshCw size={16} className="animate-spin" /> AI 编写中...</>
                  ) : (
                     <><Wand2 size={16} /> 生成代码骨架</>
                  )}
               </button>
            </div>
         </div>

         <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-5">
            <h4 className="text-sm font-medium text-slate-300 mb-3">AI 上下文感知</h4>
            <div className="flex flex-wrap gap-2 text-xs">
               <span className="px-2 py-1 bg-blue-500/10 text-blue-400 border border-blue-500/20 rounded">Windchill 11.0 API</span>
               <span className="px-2 py-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded">PersistenceHelper</span>
               <span className="px-2 py-1 bg-purple-500/10 text-purple-400 border border-purple-500/20 rounded">IBA Utils</span>
            </div>
         </div>
      </div>

      {/* Right: Code Editor */}
      <div className="lg:col-span-8 bg-black border border-slate-800 rounded-xl overflow-hidden flex flex-col">
         <div className="h-10 bg-slate-900 border-b border-slate-800 flex items-center justify-between px-4">
            <div className="flex items-center gap-2">
               <div className="flex gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/50"></div>
                  <div className="w-3 h-3 rounded-full bg-amber-500/20 border border-amber-500/50"></div>
                  <div className="w-3 h-3 rounded-full bg-emerald-500/20 border border-emerald-500/50"></div>
               </div>
               <span className="text-xs text-slate-500 ml-2 font-mono">BOMTraversalService.java</span>
            </div>
            <div className="flex items-center gap-2">
               <span className="text-[10px] text-slate-500">Java / Windchill</span>
               <button className="p-1 hover:bg-slate-800 rounded text-slate-400"><Code2 size={14}/></button>
            </div>
         </div>
         <div className="flex-1 p-4 overflow-auto font-mono text-sm leading-relaxed text-slate-300 relative">
            {isGenerating ? (
               <div className="absolute inset-0 flex items-center justify-center bg-black/50 backdrop-blur-sm z-10">
                  <div className="flex flex-col items-center gap-3">
                     <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
                     <div className="text-xs text-indigo-400 animate-pulse">正在引用 Windchill API 库...</div>
                  </div>
               </div>
            ) : generatedCode ? (
               <pre><code dangerouslySetInnerHTML={{ __html: generatedCode.replace(/public/g, '<span class="text-purple-400">public</span>').replace(/class/g, '<span class="text-purple-400">class</span>').replace(/import/g, '<span class="text-red-400">import</span>').replace(/\/\/.*/g, '<span class="text-slate-500">$&</span>').replace(/"(.*?)"/g, '<span class="text-emerald-400">"$1"</span>') }} /></pre>
            ) : (
               <div className="h-full flex flex-col items-center justify-center text-slate-700">
                  <Braces size={48} className="mb-4 opacity-20" />
                  <p>等待输入需求...</p>
               </div>
            )}
         </div>
      </div>
    </div>
  );
};

// --- Automated Testing View ---

const AutomatedTestingView = () => {
  const [activeStory, setActiveStory] = useState<string | null>(null);

  const stories = [
    { id: 'US-101', title: '用户能在部件详情页查看 ERP 库存', type: 'UI/API', risk: 'High' },
    { id: 'US-102', title: '检入文档时自动校验必填属性', type: 'Unit', risk: 'Medium' },
    { id: 'US-103', title: '批量变更申请 (ECN) 工作流路由', type: 'Integration', risk: 'High' },
  ];

  const testCases = [
    { type: 'Unit Test', code: 'WTPartTest.java', status: 'Passed', coverage: '92%' },
    { type: 'API Test', code: 'InventoryAPI_Test.json', status: 'Passed', coverage: '100%' },
    { type: 'UI Test', code: 'PartPage_Selenium.py', status: 'Running', coverage: '45%' },
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-full animate-in fade-in duration-500">
      {/* Left: User Stories */}
      <div className="lg:col-span-4 space-y-6">
         <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-5 h-full flex flex-col">
            <h3 className="font-semibold text-white mb-4 flex items-center gap-2">
               <FileJson size={18} className="text-emerald-400" />
               用户故事 (User Stories)
            </h3>
            <div className="space-y-3 flex-1">
               {stories.map(s => (
                  <div 
                     key={s.id} 
                     onClick={() => setActiveStory(s.id)}
                     className={`p-3 rounded-lg border cursor-pointer transition-all ${
                        activeStory === s.id ? 'bg-slate-800 border-indigo-500/50 shadow-lg shadow-indigo-500/10' : 'bg-slate-950 border-slate-800 hover:border-slate-700'
                     }`}
                  >
                     <div className="flex justify-between items-start mb-1">
                        <span className="text-xs font-mono text-slate-500">{s.id}</span>
                        <span className={`text-[10px] px-1.5 py-0.5 rounded ${s.risk === 'High' ? 'bg-red-500/10 text-red-400' : 'bg-amber-500/10 text-amber-400'}`}>{s.risk} Risk</span>
                     </div>
                     <div className="text-sm text-slate-200 font-medium mb-2">{s.title}</div>
                     <div className="flex items-center gap-2 text-xs text-slate-500">
                        <TestTube size={12} /> 建议: {s.type} Test
                     </div>
                  </div>
               ))}
            </div>
         </div>
      </div>

      {/* Right: Generated Test Suite */}
      <div className="lg:col-span-8 space-y-6">
         <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-5">
            <div className="flex justify-between items-center mb-6">
               <h3 className="font-semibold text-white flex items-center gap-2">
                  <ShieldCheck size={18} className="text-purple-400" />
                  AI 生成测试套件
               </h3>
               {activeStory && (
                  <button className="bg-purple-600 hover:bg-purple-500 text-white px-3 py-1.5 rounded text-xs flex items-center gap-2">
                     <Play size={12} /> 运行所有测试
                  </button>
               )}
            </div>

            {activeStory ? (
               <div className="space-y-4">
                  {testCases.map((tc, i) => (
                     <div key={i} className="bg-slate-950 border border-slate-800 rounded-lg p-4 animate-in slide-in-from-bottom-2" style={{ animationDelay: `${i * 100}ms` }}>
                        <div className="flex items-center justify-between mb-3">
                           <div className="flex items-center gap-3">
                              <div className="p-2 bg-slate-900 rounded border border-slate-700 text-slate-400">
                                 {tc.type === 'UI Test' ? <Layers size={16}/> : <Braces size={16}/>}
                              </div>
                              <div>
                                 <div className="text-sm font-medium text-slate-200">{tc.code}</div>
                                 <div className="text-xs text-slate-500">{tc.type}</div>
                              </div>
                           </div>
                           <div className="flex items-center gap-4">
                              <div className="text-right">
                                 <div className="text-xs text-slate-500">Coverage</div>
                                 <div className="text-sm font-mono text-emerald-400">{tc.coverage}</div>
                              </div>
                              <span className={`px-2 py-1 text-xs rounded border ${
                                 tc.status === 'Passed' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' : 
                                 'bg-blue-500/10 text-blue-400 border-blue-500/20 flex items-center gap-1'
                              }`}>
                                 {tc.status === 'Running' && <RefreshCw size={10} className="animate-spin" />}
                                 {tc.status}
                              </span>
                           </div>
                        </div>
                        {/* Mock Code Preview snippet */}
                        <div className="bg-black/50 rounded p-2 text-[10px] font-mono text-slate-500 overflow-hidden truncate">
                           {tc.type === 'Unit Test' ? '@Test public void testValidation() { Assert.assertTrue(...); }' : 
                            tc.type === 'UI Test' ? 'driver.find_element(By.ID, "submit_btn").click()' : '{ "method": "POST", "url": "/api/v1/parts", "body": {...} }'}
                        </div>
                     </div>
                  ))}
               </div>
            ) : (
               <div className="h-64 flex flex-col items-center justify-center text-slate-600 border-2 border-dashed border-slate-800 rounded-lg">
                  <CheckCircle2 size={32} className="mb-3 opacity-20" />
                  <p>选择左侧的用户故事以生成测试用例</p>
               </div>
            )}
         </div>
      </div>
    </div>
  );
};

// --- Data Migration View ---

const DataMigrationView = () => {
  const mappings = [
    { src: 'LEGACY_PART_NO', tgt: 'number', confidence: 0.98, status: 'Auto' },
    { src: 'MAT_SPEC_ID', tgt: 'IBA|MaterialCode', confidence: 0.85, status: 'Auto' },
    { src: 'WT_UNIT', tgt: 'defaultUnit', confidence: 0.92, status: 'Auto' },
    { src: 'V_SUPPLIER', tgt: 'SourcingContext', confidence: 0.45, status: 'Review' },
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-full animate-in fade-in duration-500">
       <div className="lg:col-span-8 space-y-6">
          <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-5">
             <div className="flex justify-between items-center mb-6">
                <h3 className="font-semibold text-white flex items-center gap-2">
                   <Shuffle size={18} className="text-orange-400" />
                   智能模型映射 (Schema Mapping)
                </h3>
                <div className="flex gap-2 text-xs">
                   <span className="px-2 py-1 bg-emerald-500/10 text-emerald-400 rounded">Auto Match: 3</span>
                   <span className="px-2 py-1 bg-amber-500/10 text-amber-400 rounded">Needs Review: 1</span>
                </div>
             </div>

             <div className="relative p-6 bg-slate-950 rounded-lg border border-slate-800 min-h-[300px]">
                {/* Headers */}
                <div className="flex justify-between text-xs text-slate-500 uppercase font-semibold mb-6">
                   <div className="w-1/3">Source (Legacy DB)</div>
                   <div className="w-1/3 text-center">AI Confidence</div>
                   <div className="w-1/3 text-right">Target (Windchill)</div>
                </div>

                <div className="space-y-6 relative z-10">
                   {mappings.map((m, i) => (
                      <div key={i} className="flex justify-between items-center group">
                         {/* Source Node */}
                         <div className="w-1/3 flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full bg-slate-600"></div>
                            <div className="px-3 py-2 bg-slate-900 border border-slate-700 rounded text-sm text-slate-300 w-full truncate">
                               {m.src}
                            </div>
                         </div>

                         {/* Connection Line Visual */}
                         <div className="flex-1 flex flex-col items-center px-4 relative">
                            <div className={`w-full h-0.5 ${m.confidence > 0.8 ? 'bg-emerald-500/50' : 'bg-amber-500/50 dashed'}`}></div>
                            <div className={`absolute top-1/2 -translate-y-1/2 px-2 py-0.5 rounded text-[10px] bg-slate-900 border ${
                               m.confidence > 0.8 ? 'border-emerald-500/50 text-emerald-400' : 'border-amber-500/50 text-amber-400'
                            }`}>
                               {Math.floor(m.confidence * 100)}%
                            </div>
                         </div>

                         {/* Target Node */}
                         <div className="w-1/3 flex items-center justify-end gap-2">
                            <div className="px-3 py-2 bg-indigo-900/20 border border-indigo-500/30 rounded text-sm text-indigo-300 w-full text-right truncate">
                               {m.tgt}
                            </div>
                            <div className="w-2 h-2 rounded-full bg-indigo-500"></div>
                         </div>
                      </div>
                   ))}
                </div>
             </div>
          </div>
       </div>

       <div className="lg:col-span-4 bg-slate-900/50 border border-slate-800 rounded-xl p-5 flex flex-col">
          <h3 className="font-semibold text-white mb-4 flex items-center gap-2">
             <AlertTriangle size={18} className="text-red-400" />
             数据质量报告
          </h3>
          <div className="flex-1 space-y-4">
             <div className="p-3 bg-slate-950 rounded-lg border border-slate-800">
                <div className="text-xs text-slate-500 mb-1">总记录数</div>
                <div className="text-xl font-bold text-white">45,210</div>
             </div>
             
             <div className="space-y-3">
                <div className="flex items-center justify-between p-2 rounded hover:bg-slate-800 transition-colors">
                   <div className="flex items-center gap-2 text-sm text-slate-300">
                      <div className="w-2 h-2 bg-red-500 rounded-full"></div> 重复记录
                   </div>
                   <div className="font-mono text-red-400">128</div>
                </div>
                <div className="flex items-center justify-between p-2 rounded hover:bg-slate-800 transition-colors">
                   <div className="flex items-center gap-2 text-sm text-slate-300">
                      <div className="w-2 h-2 bg-amber-500 rounded-full"></div> 必填缺失
                   </div>
                   <div className="font-mono text-amber-400">542</div>
                </div>
                <div className="flex items-center justify-between p-2 rounded hover:bg-slate-800 transition-colors">
                   <div className="flex items-center gap-2 text-sm text-slate-300">
                      <div className="w-2 h-2 bg-blue-500 rounded-full"></div> 格式异常
                   </div>
                   <div className="font-mono text-blue-400">12</div>
                </div>
             </div>
          </div>
          <button className="w-full mt-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded border border-slate-700 text-xs flex items-center justify-center gap-2">
             <RefreshCw size={12}/> 生成清洗脚本
          </button>
       </div>
    </div>
  );
};

// --- Main Component ---

const DevOps: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>('CODEGEN');

  const tabs: { id: Tab; label: string; icon: any }[] = [
    { id: 'CODEGEN', label: 'Windchill 代码生成器', icon: Code2 },
    { id: 'TESTING', label: '自动化测试生成', icon: TestTube },
    { id: 'MIGRATION', label: '数据迁移助手', icon: Database },
  ];

  return (
    <div className="p-6 h-full flex flex-col gap-6">
      {/* Header & Nav */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Server className="text-pink-500" />
            实施与运维效能中心
          </h2>
          <p className="text-slate-400 text-xs mt-1">
            用 AI 加速 Windchill 开发、测试与数据迁移。
          </p>
        </div>

        <div className="flex bg-slate-900 p-1 rounded-lg border border-slate-800">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2 text-xs font-medium rounded-md transition-all ${
                activeTab === tab.id 
                  ? 'bg-slate-800 text-white shadow-sm' 
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <tab.icon size={14} />
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 min-h-0 relative">
         {activeTab === 'CODEGEN' && <CodeGeneratorView />}
         {activeTab === 'TESTING' && <AutomatedTestingView />}
         {activeTab === 'MIGRATION' && <DataMigrationView />}
      </div>
    </div>
  );
};

export default DevOps;